"""Build the logo: logo.svg for the web and cli/logo.txt for text mode.

The mark is three slanted bars, ▰▰▰, coloured yellow -> orange -> red left to right like a
progress bar filling toward sunset. The SVG draws them as parallelograms; the text version
is simply three ▰ characters. tools/build_cli.py colours each one with text_rows() in
browsers that support it.

Run after editing:  python3 tools/logo.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ROWS = 3                        # bar height, in cells
BODY = 5                        # full cells between a bar's two slanted edge cells
GAP = 1                         # empty cells between bars
COLOURS = ['#ffd23f', '#f47003', '#e0262f']   # one per bar: yellow, orange, red
CELL_W, CELL_H = 8, 16          # SVG units per cell; the bars are drawn on a cell grid

BAR = BODY + 2                  # cells a bar covers on each row
COLS = len(COLOURS) * BAR + (len(COLOURS) - 1) * GAP + ROWS - 1


def bar_left(i, r):
    """Column of bar i's left edge cell on row r (0 = top); each row down steps one cell left."""
    return i * (BAR + GAP) + (ROWS - 1 - r)


def text_rows():
    """The text logo as rows of (text, colour) segments: one row, one ▰ per bar."""
    return [[('▰', colour) for colour in COLOURS]]


def text_art():
    return '\n'.join(''.join(t for t, _ in row) for row in text_rows()) + '\n'


def svg():
    h = ROWS * CELL_H
    bars = []
    for i, colour in enumerate(COLOURS):
        # left edge runs from the bottom-left of the bottom row's edge cell to the top-right
        # of the top row's edge cell; the right edge is the same line BAR - 1 cells over
        bl = bar_left(i, ROWS - 1) * CELL_W
        tl = (bar_left(i, 0) + 1) * CELL_W
        span = (BAR - 1) * CELL_W
        bars.append(f'<path fill="{colour}" d="M{bl} {h}L{tl} 0H{tl + span}L{bl + span} {h}Z"/>')
    body = '\n  '.join(bars)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {COLS * CELL_W} {h}" role="img" aria-labelledby="dpf-logo-title">
  <title id="dpf-logo-title">DPForesi</title>
  <!-- generated by tools/logo.py, which also writes the matching cli/logo.txt -->
  {body}
</svg>
'''


if __name__ == '__main__':
    art = text_art()
    with open(os.path.join(ROOT, 'logo.svg'), 'w', encoding='utf-8') as f:
        f.write(svg())
    with open(os.path.join(ROOT, 'cli', 'logo.txt'), 'w', encoding='utf-8') as f:
        f.write(art)
    print(art, end='')
    print('\nwrote logo.svg and cli/logo.txt')
